#!/bin/bash

### gitn Usage:help
#
# Shorthands for git workflows
#
###/doc

#%include githelpers/calling.sh githelpers/branching.sh
#%include arguments.sh settings.sh
#%include bashout.sh

#%include actions/diff.sh actions/commit.sh
#%include actions/status.sh actions/fetch.sh
#%include actions/pull.sh actions/push.sh
#%include actions/remote.sh

function main {
	settings_load
	args_processargs "$@"

	case "$GITARGS_action" in
	status)
		action_status ;;
	commit)
		action_commit ;;
	diff)
		action_diff ;;
	push)
		action_push ;;
	pull)
		action_pull ;;
	branch)
		action_branch ;;
	remote)
		action_remote ;;
	merge)
		action_merge ;;
	update)
		action_update ;;
	*)
		faile "Action $GITARGS_action not yet available"
		;;
	esac
}

if [[ "$NORUN" != norun ]]; then
	main "$@"
fi
