#!/bin/bash

### gitn Usage:help
#
# Shorthands for git workflows
#
###/doc

#%include notest.sh

#%include help.sh autohelp.sh

#%include githelpers/calling.sh githelpers/branching.sh githelpers/commits.sh
#%include arguments.sh settings.sh
#%include bashout.sh

#%include actions/diff.sh actions/commit.sh
#%include actions/status.sh actions/fetch.sh
#%include actions/pull.sh actions/push.sh
#%include actions/remote.sh actions/branch.sh
#%include actions/merge.sh actions/patch.sh
#%include actions/log.sh actions/blame.sh
#%include actions/stash.sh actions/checkout.sh
#%include actions/tag.sh actions/release.sh

function main {
	settings_load
	args_processargs "$@"

	case "$GITARGS_action" in
	status)
		action_status ;;
	commit)
		action_commit ;;
	diff)
		action_diff ;;
	push)
		action_push ;;
	pull)
		action_pull ;;
	branch)
		action_branch ;;
	remote)
		action_remote ;;
	merge)
		action_merge ;;
	update)
		action_update ;;
	checkout)
		action_checkout ;;
	stash)
		action_stash ;;
	tag)
		action_tag ;;
	release)
		action_release ;;
	log)
		action_log ;;
	blame)
		action_blame ;;
	patch)
		action_patch ;;
	*)
		faile "Action $GITARGS_action not yet available"
		;;
	esac
}

notest main "$@"
